#!/usr/bin/env python3
"""Generate BesselReference.hpp using mpmath (offline only; no build dependency).

Inputs are exact binary floating-point values. Dyadic decimal inputs are parsed
from strings; root neighbors intentionally use rounded float/double coordinates.
Every coordinate is converted to an exact integer ratio before reference evaluation.
The stored binary64 references must agree after increasing working precision by
80 decimal digits. Ordinary cases start at 100 digits; very large arguments use
additional precision to resolve their phase and exponential scale reliably.

Run: python3 include/pmacc/test/math/bessel_reference.py
"""
# Copyright 2026 Alexander Debus and LLM agent
# SPDX-License-Identifier: LGPL-3.0-or-later

from pathlib import Path
import math
import struct

import mpmath as mp


def exact(value):
    numerator, denominator = value.as_integer_ratio()
    return mp.mpf(numerator) / denominator


def float32(value):
    return struct.unpack("f", struct.pack("f", value))[0]


def cases():
    # All common coordinates are exactly representable in both float and double.
    common = [(0.0, 0.0, True), (2.0**-100, 0.0, True), (0.0, 2.0**-100, True),
              (2.0**-100, 2.0**-100, True)]
    common += [(float(x), float(y), True) for x, y in [
        ("0.5", "0.25"), ("1", "2"), ("3", "4"),
        ("3.9990234375", "0"), ("4", "0"), ("4.0009765625", "0"),
        ("0", "3.9990234375"), ("0", "4"), ("0", "4.0009765625"),
        ("8", "0"), ("8", "8"), ("11.9990234375", "0"),
        ("12", "0"), ("12.0009765625", "0"),
        ("0", "11.9990234375"), ("0", "12"), ("0", "12.0009765625"),
        ("12", "0.0009765625"), ("20", "0"), ("24", "8"),
        ("31.9990234375", "0"), ("32", "0"), ("32.0009765625", "0"),
        ("0", "31.9990234375"), ("0", "32"), ("0", "32.0009765625"),
        ("32", "0.0009765625"), ("35", "0"), ("50", "0"),
        ("3", "49.9990234375"), ("3", "50"), ("3", "50.0009765625"),
        ("0", "80"), ("3", "80"), ("0", "90"), ("3", "90"), ("0", "91"),
    ]]
    common += [(2.0**20, 0.0, True), (2.0**60, 3.0, True), (2.0**120, 0.0, True)]
    common += [(x, y, False) for x, y in [(0., 100.), (3., 1000.), (0., 1000.), (3., 10000.)]]
    double = [(2.0**-700, 0., True), (0., 2.0**-700, True), (2.0**-700, 2.0**-700, True),
              (0., 700., True), (3., 700., True), (0., 710., True), (3., 710., True),
              (0., 713., True), (3., 713., True),
              (2.0**700, 0., True), (2.0**700, 2.0**699, False), (0., 2.0**700, False)]
    with mp.workdps(100):
        for order in (0, 1):
            root = mp.besseljzero(order, 1)
            xf = float32(root)
            common += [(xf + d, y, True) for d in (-2.0**-20, 0., 2.0**-20) for y in (0., 2.0**-20)]
            xd = float(root)
            double += [(x, y, True) for x in (math.nextafter(xd, -math.inf), xd, math.nextafter(xd, math.inf))
                       for y in (0., 2.0**-50)]
    for boundary in (4., 12., 32.):
        double += [(v, 0., True) for v in (math.nextafter(boundary, -math.inf), math.nextafter(boundary, math.inf))]
    return common, double


def reference(x, y, unscaled, digits):
    with mp.workdps(digits):
        z = mp.mpc(exact(x), exact(y))
        j = [mp.besselj(n, z) for n in (0, 1)]
        scaled = [v * mp.exp(-abs(z.imag)) for v in j]
        values = (j if unscaled else [mp.mpc(0), mp.mpc(0)]) + scaled
        return tuple(float(part) for v in values for part in (v.real, v.imag))


def generate():
    lines = ["// Copyright 2026 Alexander Debus and LLM agent",
             "// SPDX-License-Identifier: LGPL-3.0-or-later",
             "// Generated by bessel_reference.py; do not edit reference values by hand.",
             "#pragma once", "#include <array>", "namespace besselTest", "{",
             "struct Reference", "{", "    double real;", "    double imag;", "    bool unscaled;",
             "    // J0, J1, exp(-abs(Im(z)))*J0, exp(-abs(Im(z)))*J1; real/imaginary components.",
             "    std::array<double, 8u> values;", "};", "// clang-format off"]
    for name, inputs in zip(("common", "doubleOnly"), cases()):
        lines.append(f"inline constexpr std::array<Reference, {len(inputs)}u> {name}{{{{")
        for x, y, unscaled in inputs:
            # Resolve both phase at huge arguments and small components of nearly real results.
            nonzero = [abs(v) for v in (x, y) if v != 0.]
            digits = max(100, int(math.log10(max(1., abs(x), abs(y)))) + 80,
                         int(-2 * math.log10(min(nonzero))) + 80 if nonzero else 100)
            ref = reference(x, y, unscaled, digits)
            assert ref == reference(x, y, unscaled, digits + 80), (x, y, "unstable reference")
            values = [format(v, ".17e") for v in ref]
            lines += [f"    {{{x.hex()}, {y.hex()}, {'true' if unscaled else 'false'},",
                      "     {" + ", ".join(values[:4]) + ",",
                      "      " + ", ".join(values[4:]) + "}},"]
        lines.append("}};")
    lines += ["// clang-format on", "} // namespace besselTest", ""]
    Path(__file__).with_name("BesselReference.hpp").write_text("\n".join(lines))


if __name__ == "__main__":
    generate()
